name: Build-APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev openjdk-17-jdk autoconf automake libtool pkg-config zlib1g-dev libasound2-dev libpulse-dev unzip zip
          pip install --upgrade pip
          pip install "cython<3.0.0" wheel
          pip install buildozer

      - name: Auto-Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # Buildozer ke khud ke downloaded sdkmanager ko dhund kar use chalana
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          if [ -d "$ANDROID_HOME/cmdline-tools/latest/bin" ]; then
            yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          fi

      - name: Run Buildozer Build
        run: |
          rm -rf .buildozer/android/platform/python-for-android
          mkdir -p .buildozer/android/platform/
          git clone --branch master https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
          # Buildozer automatically prompts for licenses if run with 'yes'
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snake-Game-APK
          path: bin/*.apk
          
